openapi: 3.0.3
info:
  title: CitaLink API
  version: 1.0.0
  description: API para gestionar citas con pago de anticipo para clínicas.
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://staging.citalink.com
    description: Staging server
  - url: https://api.citalink.com
    description: Production server

tags:
  - name: Authentication
    description: Endpoints para registro, login y gestión de sesión.
  - name: Appointments
    description: Operaciones para crear y gestionar CitaLinks.
  - name: Clinic
    description: Gestión de la configuración de la clínica.
  - name: Payments
    description: Endpoints relacionados con el procesamiento de pagos.
  - name: Webhooks
    description: Endpoints para recibir notificaciones de servicios externos.

paths:
  /api/auth/register:
    post:
      tags: [Authentication]
      summary: Registrar una nueva clínica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Clínica creada exitosamente. Devuelve un token de sesión.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/auth/login:
    post:
      tags: [Authentication]
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login exitoso. Devuelve un token de sesión.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccessResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/appointments:
    get:
      tags: [Appointments]
      summary: Obtener la lista de CitaLinks de la clínica
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de appointments.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [Appointments]
      summary: Crear un nuevo CitaLink
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppointmentRequest'
      responses:
        '201':
          description: Appointment creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/appointments/{id}/pay:
    post:
      tags: [Payments]
      summary: Procesar el pago de un CitaLink
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethodId:
                  type: string
              required: [paymentMethodId]
      responses:
        '200':
          description: Pago procesado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/clinic/settings:
    get:
      tags: [Clinic]
      summary: Obtener la configuración de la clínica
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Configuración actual de la clínica.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicSettings'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags: [Clinic]
      summary: Actualizar la configuración de la clínica
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicSettings'
      responses:
        '200':
          description: Configuración actualizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicSettings'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/webhooks/stripe:
    post:
      tags: [Webhooks]
      summary: Recibir eventos de Stripe
      description: Endpoint para que Stripe envíe webhooks (ej. payment_intent.succeeded).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Stripe event object
      responses:
        '200':
          description: Webhook recibido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  received:
                    type: boolean
                    example: true
        '400':
          description: Error al procesar el webhook (ej. firma inválida).

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        clinicName:
          type: string
          example: "Clínica Dental Sonrisas"
        email:
          type: string
          format: email
          example: "admin@sonrisas.com"
        password:
          type: string
          format: password
          minLength: 8
          example: "Password123"
      required: [clinicName, email, password]

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required: [email, password]

    AuthSuccessResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT para autenticar peticiones.
        user:
          $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        clinicId:
          type: string
          format: uuid

    Appointment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        clinicId:
          type: string
          format: uuid
        patientName:
          type: string
        status:
          type: string
          enum: [pending, confirmed, expired]
        totalAmount:
          type: number
          format: float
        depositAmount:
          type: number
          format: float
        appointmentDate:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    CreateAppointmentRequest:
      type: object
      properties:
        patientName:
          type: string
          example: "Juan Pérez"
        appointmentDate:
          type: string
          format: date-time
          example: "2025-12-10T15:30:00Z"
        totalAmount:
          type: number
          format: float
          example: 150.00
      required: [patientName, appointmentDate, totalAmount]

    ClinicSettings:
      type: object
      properties:
        defaultDepositPercentage:
          type: integer
          minimum: 1
          maximum: 100
          example: 20
        messageTemplate:
          type: string
          maxLength: 500
          example: "Hola [nombre_paciente], confirma tu cita en el siguiente enlace: [link]"
        defaultExpirationHours:
          type: integer
          minimum: 1
          example: 48

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "VALIDATION_ERROR"
            message:
              type: string
              example: "El campo 'email' es inválido."

  responses:
    BadRequest:
      description: Error de validación o petición mal formada.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: No autenticado. El token JWT es inválido o no fue proporcionado.
    NotFound:
      description: El recurso solicitado no fue encontrado.

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
